CircleCI 2.0 configuration file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv rain
            . rain/bin/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . rain/bin/activate
            bash run_tests.sh